### PR TITLE
core framework and ~90% functionality for cluster-tools v0.1

### PR DESCRIPTION
**Pull request by paxtonfitzpatrick**
```
vpn ➜  clustertools git:(master) ✗ tree .
.
├── __init__.py
├── cluster.py
├── file_objects
│   ├── __init__.py
│   ├── configs
│   │   ├── __init__.py
│   │   ├── base_config.py
│   │   ├── config_helpers.py
│   │   ├── global_config.py
│   │   ├── project_config.py
│   │   └── tracked_attr_config.py
│   ├── project_script.py
│   └── synced_file.py
├── project
│   ├── __init__.py
│   ├── job.py
│   ├── project.py
│   └── project_handler.py
├── shared
│   ├── __init__.py
│   ├── environ.py
│   ├── exceptions.py
│   ├── helpers.py
│   ├── multistream_wrapper.py
│   ├── object_monitors.py
│   ├── remote_process.py
│   └── typing.py
├── shells
│   ├── __init__.py
│   ├── base_shell.py
│   ├── local_shell.py
│   └── ssh_shell.py
└── templates
    ├── __init__.py
    ├── global_config.ini
    ├── monitor.py
    ├── project_config.ini
    ├── submit_old.py
    └── submitter.py

7 directories, 38 files
```

### CODE REVIEW

**Comment by jeremymanning** [comment]
@paxtonfitzpatrick do you want me to merge?

**Comment by paxtonfitzpatrick** [comment]
sorry! I went ahead and did it since it's not the master branch

**Comment by jeremymanning** [comment]
ah-- i guess so!

**Comment by jeremymanning** [comment]
no prob; didn't know if you had write access

**Pull request merged**
